### ISSUE TITLE
License

### ISSUE THREAD

**Issue by antagomir** [steadyfish/ogdindiar#10]
The ./inst/extras/build.cran.sh (from my recent pull request) says:
- checking DESCRIPTION meta-information ... NOTE
  License components which are templates and need '+ file LICENSE':
  MIT

To declare license (MIT is fine) you need to follow the convention that you can check for instance here:
https://github.com/ropengov/eurostat/blob/master/DESCRIPTION

So modify your DESCRIPTION file License field in the same as there, and also add the file named LICENSE to the same root directory where you have the DESCRIPTION file
https://github.com/ropengov/eurostat/blob/master/LICENSE

**Comment by steadyfish** [comment]
Updated as in `eurostat` package
