### ISSUE TITLE
Are you still developping this package? + another question

### ISSUE THREAD

**Issue by maelle** [steadyfish/ogdindiar#14]
Hi,

I've just installed your R package and I'm very happy you've written it, thanks a lot!

I see that there is not much activity on the repo, so I wonder whether you're still developping this package? I hope you are because it can be very useful. 

My other question is whether you think it would be possible to add a search function, i.e. for finding datasets IDs based on e.g. keywords?

Anyway, thanks again for making this package available! :-)

**Comment by steadyfish** [comment]
@masalmon I'm happy it's useful to you :)

I haven't worked on this package for a while but wouldn't mind resuming. If you have any features you'd like implemented in this package, do let me know.

Reg. your question about datasets, currently there isn't a function to do that. Nonetheless, you can look up all the datasets that are available through an API here - https://data.gov.in/catalogs#path=is_api/1

I had thought about scrapping this webpage and making the list of datasets available as part of the package but haven't worked much on it yet.

**Comment by maelle** [comment]
Cool you're still kind of active!

I guess having a function that return a table of datasets based on e.g. keywords would be a very useful addition to your package! If you have time some day. ;-)

Anyway thanks for your answer!

**Comment by sainathadapa** [comment]
I am also interested in the search functionality. I can work on it. Will you accept a pull request towards that functionality?

**Comment by steadyfish** [comment]
@sainathadapa Thanks for offering to contribute.

Finding datasets available through an API, based on keywords instead of a resource id would be fairly useful addition to this package! Let me know your thoughts on the implementation.

**Comment by maelle** [comment]
@sainathadapa it'd be awesome if you added the functionality! I promise I'd test it! :smiley:

**Comment by sainathadapa** [comment]
This is a rough idea of how I want to implement the search functionality. Since there is no current API endpoint to implement search, I had to resort to html scraping. Let me know your thoughts @steadyfish @masalmon 

```
library(stringr)
library(dplyr)
library(rvest)

mk_link <- . %>% paste0("https://data.gov.in", .)

extract_catalogs_from_search_result <- function(parsed_html) {
  link_nodes <- parsed_html %>% html_nodes(css = '.title a')

  link_data <- data.frame(name = html_text(link_nodes), link = html_attr(link_nodes, 'href'), stringsAsFactors = FALSE)

  link_data <- link_data %>% 
    mutate(category = dirname(link) %>% str_replace(pattern = '^/', replacement = ''))

  link_data %>% filter(category %in% 'catalog')
}

extract_data_sets_from_catalog_link <- function(catalog_link) {
  this_catalog_link <- read_html(mk_link(catalog_link))

  csv_links <- this_catalog_link %>% html_nodes(css = '.data-extension') %>% html_attr('href')

  csv_names <- this_catalog_link %>% html_nodes(css = '.title-content') %>% html_text

  data.frame(name = csv_names, link = csv_links)
}

search_for_data_sets <- function(search_term) {

  first_search_result <- read_html(mk_link(paste0("/search/site/", search_term)))

  next_pages_links <- first_search_result %>% html_nodes(css = '.pager-item a') %>% html_attr('href')

  next_pages_results <- lapply(next_pages_links, . %>% mk_link %>% read_html)

  catalogs_from_all_search_pages <- c(list(first_search_result), next_pages_results) %>% 
    lapply(extract_catalogs_from_search_result) %>% 
    do.call(what = rbind, args = .)

  lapply(catalogs_from_all_search_pages$link, extract_data_sets_from_catalog_link) %>% 
    do.call(what = rbind, args = .)
}

ans <- search_for_data_sets('train')
```

**Comment by maelle** [comment]
@sainathadapa I see you use rvest, it sounds like a neat package. You're scraping a whole webpage and the code still is readable!

Is your code supposed to work? On my machine it kept running and did not output anything (I stopped it after >1h). But I realize it's a draft more than a code.

Otherwise it looks great. How would you deal with queries having more than one word, would you expect the user to input a vector of words and then have the function past them? And what will the function return if there are no results?

**Comment by sainathadapa** [comment]
@masalmon The code is supposed to work. I ran it just now, and it finished in less than 30s. Is https://data.gov.in accessible from your location? Or did you use another search term, possibly with tens of pages of results? I have also uploaded the result from the above code at https://gist.github.com/sainathadapa/c122ced23381ce81d50cc21b6fc115a0. 

As to queries with multiple words, the function can either require a character vector or a single string with words separated by space. The function will then split them on space (or some other separator). If there are no results, the function will return a data.frame with zero rows. (or NULL, I am not sure yet).

**Comment by maelle** [comment]
I'm letting it run again then -- still gets blocked. Interestingly I can access the website and do the query and it's faster. 

``` r
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rvest_0.3.1     xml2_0.1.2.9000 dplyr_0.4.3     stringr_1.0.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4          XML_3.98-1.4         assertthat_0.1       R6_2.1.2            
 [5] DBI_0.3.1.9008       magrittr_1.5         httr_1.1.0           stringi_1.0-1       
 [9] curl_0.9.6           lazyeval_0.1.10.9000 tools_3.2.3          selectr_0.2-3       
[13] parallel_3.2.3       rsconnect_0.4.1.11  

```

**Comment by sainathadapa** [comment]
hmm. This is my sessionInfo() output:

```
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rvest_0.3.1   xml2_0.1.2    dplyr_0.4.3   stringr_1.0.0

loaded via a namespace (and not attached):
 [1] httr_1.1.0      selectr_0.2-3   lazyeval_0.1.10 R6_2.1.2        assertthat_0.1  magrittr_1.5   
 [7] parallel_3.2.4  DBI_0.3.1       tools_3.2.4     curl_0.9.6      Rcpp_0.12.4     stringi_1.0-1  
[13] XML_3.98-1.4   
```

Possible reasons that I can think of:
- You seem to be using the development version of xml2 and lazyeval. 
- You have a way faster internet connection than mine,  and the site is blocking multiple requests that occur within few milliseconds gap

Can you try adding `Sys.sleep(1)` before calls to read_html function? If it doesn't work, try removing xml2 and lazyeval, and install the stable version from CRAN.

**Comment by maelle** [comment]
With Sys.sleep() do you mean

``` r
library(stringr)
library(dplyr)
library(rvest)

mk_link <- . %>% paste0("https://data.gov.in", .)

extract_catalogs_from_search_result <- function(parsed_html) {
  link_nodes <- parsed_html %>% html_nodes(css = '.title a')

  link_data <- data.frame(name = html_text(link_nodes), link = html_attr(link_nodes, 'href'), stringsAsFactors = FALSE)

  link_data <- link_data %>% 
    mutate(category = dirname(link) %>% str_replace(pattern = '^/', replacement = ''))

  link_data %>% filter(category %in% 'catalog')
}

extract_data_sets_from_catalog_link <- function(catalog_link) {
  Sys.sleep(1)
  this_catalog_link <- read_html(mk_link(catalog_link))

  csv_links <- this_catalog_link %>% html_nodes(css = '.data-extension') %>% html_attr('href')

  csv_names <- this_catalog_link %>% html_nodes(css = '.title-content') %>% html_text

  data.frame(name = csv_names, link = csv_links)
}

search_for_data_sets <- function(search_term) {
  Sys.sleep(1)
  first_search_result <- read_html(mk_link(paste0("/search/site/", search_term)))

  next_pages_links <- first_search_result %>% html_nodes(css = '.pager-item a') %>% html_attr('href')
  Sys.sleep(1)
  next_pages_results <- lapply(next_pages_links, . %>% mk_link %>% read_html)

  catalogs_from_all_search_pages <- c(list(first_search_result), next_pages_results) %>% 
    lapply(extract_catalogs_from_search_result) %>% 
    do.call(what = rbind, args = .)

  lapply(catalogs_from_all_search_pages$link, extract_data_sets_from_catalog_link) %>% 
    do.call(what = rbind, args = .)
}

ans <- search_for_data_sets('train')
```

**Comment by maelle** [comment]
It worked!!

**Comment by maelle** [comment]
I didn't even know I had a too fast internet connection... You might want to add this Sys.sleep thing in the function by default ;-)

**Comment by sainathadapa** [comment]
Cool. Yeah, had a similar problem before, with web scraping projects.

**Comment by maelle** [comment]
Two quick questions:
- ans could be a tbl_df from dplyr?
- could you get other info about each dataset to put in the table? Maybe size, description?

**Comment by maelle** [comment]
oh and it lacks the ID for then using the function of the ogdindiar package. ;-)

**Comment by maelle** [comment]
in any case, great scraping job!

**Comment by sainathadapa** [comment]
1) tbl_df is just a wrapper around data.frame. I personally don't care about it that much, but if rest of the functions from this package (ogdindiar) return tbl_df, then the search function also should return the same class object.
2) Any info that is displayed for each data set can be extracted. 
3) ID is available from the 'Data API' link that is present for each data set. Can be extracted.

**Comment by maelle** [comment]
1) I just like that if you print a tbl_df, it looks nice. I don't even remember what ogdindiar outputs. I'll made a PR with dplyr::tbl_df() in all functions if needed :-D
2) and 3) (I'm merging your points hehe) Cool! BTW we'd need a column API with a logical since not all these data have API access or should the function directly only queries API=true? (@steadyfish mentioned  https://data.gov.in/catalogs#path=is_api/1 at the beginning of the thread)

**Comment by sainathadapa** [comment]
I don't think https://data.gov.in/search/site/train#path=is_api works. @steadyfish Do you know of any other "unknown" URL parameters which may be useful in this case? We can always check the page for data sets in the function, and return only the ones with API access. And even the non-API accessible data can be downloaded directly using download.file, isn't it? Why limit the results.

**Comment by maelle** [comment]
"Why limit the results?" You're right, no reason. 

Reg. download.file would you save it in current directory and then read it with readr::read something and then erase the temporary file? How to know wich readr function to use, i.e. which format the file has (e.g. "," vs ";" csv)? It would make life much easier for the user not to have to think a lot, i.e.
- the user searches for a keyword
- for each possible data file using a single function the user gets a data.frame or a list of data.frames corresponding to the data file without having to think of separators.

Do you think it's possible? I guess for each file it depends on the available "EXPORT IN" format + I don't know how automatic the parsing can get.

**Comment by maelle** [comment]
This obviously means a lot of work. ;-)

**Comment by sainathadapa** [comment]
Interesting, there are only a few formats in which data.gov.in exports data. Certainly worth exploring. I will first get the basic search functionality to a "neat" stage, and then the functionality can be improved in stages.

**Comment by maelle** [comment]
That's awesome! It'll be so great to have better access to this data treasure data.gov.in is!

**Comment by steadyfish** [comment]
Hey @sainathadapa,

The code looks good and we can utilise it to address issue #3 . There, I was thinking of compiling a list of all available datasets (especially the ones that are not available through an API). We can just provide the search functionality based on the functions you wrote above, instead of having a precompiled static list of datasets. 

For this specific issue we can utilize slightly different urls of the form `https://data.gov.in/catalogs?query=train#path=is_api/1`. This would allow us to limit the search just to catalogs/datasets available through API. 

What do you guys think? @masalmon @sainathadapa

**Comment by sainathadapa** [comment]
Sounds good @steadyfish. I will start working.

**Comment by maelle** [comment]
I guess I can close this now.
