### ISSUE TITLE
fetch_data() is not downloading data.

### ISSUE THREAD

**Issue by sant1975** [steadyfish/ogdindiar#19]
When you try to fetch data via fetch_data(res_id = "<resource id>"),
data does not get downloaded and metadata gets downloaded at its place.I seems JSON structure is changed in thereceived data and we are not looking at the right element of the list for the data.
Thanks
Santosh

**Comment by sainathadapa** [comment]
I created a pull request that solves your issue. Thanks for reporting the bug! Until the pull request is merged into this repo, you can install the ogdindiar package from my fork `devtools::install_github("sainathadapa/ogdindiar")`

**Comment by sainathadapa** [comment]
@steadyfish can you review the pull request and merge it?
