### ISSUE TITLE
ogdindiar for R version 3.1.1

### ISSUE THREAD

**Issue by subinoy** [steadyfish/ogdindiar#6]
Hi, 
Could you just make the package available for R version 3.1.1. Since, I don't have the 3.2.0 version of R for my system yet (Mac OSX 10.7.5).

Thanks,

Subinoy

**Comment by steadyfish** [comment]
Hey @subinoy 

I've changed R version requirement to 3.1.1. Let me know if this works.

**Comment by subinoy** [comment]
Hi @steadyfish 

Yes, It's now working fine. Thanks !!
